#!/bin/bash

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Joshua Haveman
#
# This software is released under the MIT License, and is provided as is, without warranty.
# Modify & distribute freely.

set -eu

# Find script dir
if [ -z "${GIT_SCRIPTS_HOME_DIR:-}" ]; then
    GIT_SCRIPTS_HOME_DIR=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")
    export GIT_SCRIPTS_HOME_DIR
fi
# Source util script
. "$GIT_SCRIPTS_HOME_DIR/lib/git-core-utils.sh"

require_branch
PS_MODE="${1:-}"
case "$PS_MODE" in
force | -F | --force-with-lease)
    PS_MODE="force"
    shift
    ;;
-u)
    PS_MODE="default"
    shift
    ;;
*)
    PS_MODE="default"
    ;;
esac

case $PS_MODE in
default)
    detect_protected_branch "push"
    conditional_rb_pull
    git push -u "$REMOTE" "$working_branch"
    ;;
force)
    detect_protected_branch "push"
    git push --force-with-lease "$REMOTE" "$working_branch"
    ;;
esac
