#!/bin/bash

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Joshua Haveman
#
# This software is released under the MIT License, and is provided as is, without warranty.
# Modify & distribute freely.

set -eu

# Find script dir
if [ -z "${GIT_SCRIPTS_HOME_DIR:-}" ]; then
    GIT_SCRIPTS_HOME_DIR=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")
    export GIT_SCRIPTS_HOME_DIR
fi
# Source util script
. "$GIT_SCRIPTS_HOME_DIR/lib/git-core-utils.sh"

QC_MODE="${1:-}"
case "$QC_MODE" in
p)
    shift
    ;;
-p | push)
    QC_MODE="p"
    shift
    ;;
*)
    QC_MODE=""
    ;;
esac

[ "$QC_MODE" = "p" ] && require_branch
detect_protected_branch "commit"
commit_function "$@"
conditional_rb_pull

if [ "$QC_MODE" = "p" ]; then
    git push -u "$REMOTE" "$working_branch"
fi
