#!/bin/bash

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Joshua Haveman
#
# This software is released under the MIT License, and is provided as is, without warranty.
# Modify & distribute freely.

set -eu

# Find script dir
if [ -z "${GIT_SCRIPTS_HOME_DIR:-}" ]; then
    GIT_SCRIPTS_HOME_DIR=$(dirname -- "$(readlink -f -- "${BASH_SOURCE[0]}")")
    export GIT_SCRIPTS_HOME_DIR
fi
# Source util script
. "$GIT_SCRIPTS_HOME_DIR/lib/git-core-utils.sh"

# MAIN
info "Fetching all remotes and pruning dead branches..."
git fetch --all --prune --tags
__SYNCED=1 # already fetched, stop rb_pull_function from fetching again
rb_pull_function "$@"
