#!/bin/bash

# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2026 Joshua Haveman
#
# This software is released under the MIT License, and is provided as is, without warranty.
# Modify & distribute freely.

set -eu

# Find script dir
if [ -z "${GIT_SCRIPTS_HOME_DIR:-}" ]; then
    script_path=${BASH_SOURCE[0]}
    case $script_path in
        */*) script_dir=${script_path%/*} ;;
        *) script_dir=. ;;
    esac
    
    GIT_SCRIPTS_HOME_DIR=$(cd "$script_dir" && pwd)
    export GIT_SCRIPTS_HOME_DIR
fi
# Source util script
. "$GIT_SCRIPTS_HOME_DIR/lib/git-core-utils.sh"

rb_pull_function "$@"